language: javascript

services:
  - docker

script:
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build
  - docker-compose -f docker-compose-build.yml build --parallel
  # Do similar for other three images

  # Tagging
  - docker tag udagram-api-feed bbamii/udagram-api-feed:v1
  - docker tag udagram-api-user bbamii/udagram-api-user:v1
  - docker tag udagram-frontend bbamii/udagram-frontend:v1
  - docker tag udagram-reverseproxy bbamii/udagram-reverseproxy:v1
  # Do similar for other three images

  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - docker push bbamii/udagram-api-feed:v1
  - docker push bbamii/udagram-api-user:v1
  - docker push bbamii/udagram-frontend:v1
  - docker push bbamii/udagram-reverseproxy:v1
